services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 90s
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysdlc_net

  backend:
    image: ghcr.io/erichutabarat/mysdlc-backend:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET: ${JWT_SECRET}
      TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY}
    ports:
      - "8080:8080"
    networks:
      - mysdlc_net

  frontend:
    image: ghcr.io/erichutabarat/mysdlc_frontend:latest
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_CAPTCHA_SITE_KEY: ${NEXT_PUBLIC_CAPTCHA_SITE_KEY}
    ports:
      - "3000:3000"
    networks:
      - mysdlc_net

volumes:
  mysql_data:

networks:
  mysdlc_net: